spring:
  application:
    name: auth-bff

  # OAuth2 Client Configuration
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI}
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: preferred_username

  # Redis Configuration for Session Storage
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Session Configuration
  session:
    store-type: redis
    timeout: 30m
    redis:
      flush-mode: on_save
      namespace: spring:session

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        name: BFFSESSIONID
        http-only: true
        secure: ${COOKIE_SECURE:false}
        same-site: lax
        max-age: 1800

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.auth_bff: INFO
    # Spring Security関連のログは警告以上のみ
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.springframework.session: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Keycloak Configuration
keycloak:
  # issuer-uri（Spring Securityの設定と共通）
  issuer-uri: ${KEYCLOAK_ISSUER_URI}
  # 注: 現在の実装では、BFFがバックエンドからWebClientでKeycloakにログアウトリクエストを送信するため、
  # post_logout_redirect_uriはブラウザには届きません。フロントエンド側で独自にリダイレクト処理を実装してください。
  post-logout-redirect-uri: ${KEYCLOAK_POST_LOGOUT_REDIRECT_URI}

# Application Configuration
app:
  # フロントエンドURL
  frontend:
    url: ${FRONTEND_URL}
  # リソースサーバーURL
  resource-server:
    url: ${RESOURCE_SERVER_URL}
    # タイムアウト設定（秒）
    # WebClient経由のリソースサーバーへの接続・読み込み・書き込みタイムアウト
    timeout: ${RESOURCE_SERVER_TIMEOUT:30}
  # CORS許可オリジン
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

# Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized